name: valid

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: nimble install -y
      - name: GenBook
        run: nimble genbook
      - name: Save PR number
        run: |
          echo ${{ github.event.number }} > ./docs/NR
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.head_ref }}
          path: docs/
          retention-days: 1
          if-no-files-found: error

